### ISSUE TITLE
"http" urls  not automatically redirecting to "https"

### ISSUE THREAD

**Issue by jeromeZestyIO** [zesty-io/nextjs-website#1363] opened 2022-11-14 16:38 UTC
"http" not automatically redirecting to "https"

![Screenshot 2022-11-15 003550](https://user-images.githubusercontent.com/115722439/201715265-3daaaaef-1cee-4a6e-af98-f711dacbf6f5.png)

**Comment by glespinosa** [comment] 2022-11-17 07:56
Duplicate of this https://github.com/zesty-io/website/issues/645

**Closed as completed** 2023-11-20 06:19 UTC
